version: "3.7"
services:
  otusweb:
    image: otusweb
    container_name: otusweb
    restart: always
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./staticfiles:/var/www/app/static
      - ./media:/var/www/app/media
    ports:
     - "9092:80"
  otusdb:
    image: postgres:11
    container_name: otusdb
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - settings/database.env
  otusapp:
    build: .
    image: otusapp
    container_name: otusapp
    restart: always
    command: ["./wait-for-it.sh", "otusdb:5433", "--", "sh", "-c", "./entrypoint.sh"]
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      env: 'production'
    depends_on:
      - otusdb

networks:
  default:
    name: otus