# Generated by Django 3.1.3 on 2020-11-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'User'), (5, 'Admin'), (9, 'Developer')], default=1),
        ),
    ]
