# Generated by Django 3.1.3 on 2020-11-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
