"""Init

Revision ID: ca2fdea6441c
Revises: 
Create Date: 2020-09-16 19:59:32.636986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2fdea6441c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_request', sa.Date(), nullable=False),
    sa.Column('usd', sa.Float(precision=8), nullable=True),
    sa.Column('eur', sa.Float(precision=8), nullable=True),
    sa.Column('gbp', sa.Float(precision=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
