
name: Run python test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd task10
          pipenv install
      - name: Install dependencies
        run: |
          cd task10
          pipenv sync
      - name: Run pytest
        run: |
          cd task10
          pytest -s -vv
